version: '2.0'

services:
  gord1:
    build: .
    ports:
      - "20001:20001"
    command: "1"
  gord2:
    #build: .
    image: gordoverlay_gord1:latest
    depends_on:
      - gord1
    ports:
      - "20005:20005"
    command: "2"
  gord3:
    #build: .
    image: gordoverlay_gord1:latest
    depends_on:
      - gord1
      - gord2
    ports:
      - "20009:20009"
    command: "3"