version: '2.0'

services:
  gord1:
    build: .
    ports:
      - "26040:26040"
      - "26041:26041"
    environment:
      NODE_HOST: "gord1"
  gord2:
    build: .
    ports:
      - "36040:26040"
      - "36041:26041"
    environment:
      NODE_HOST: "gord2"
      EXIST_NODE_HOST: "gord1"
  gord3:
    build: .
    ports:
      - "46040:26040"
      - "46041:26041"
    environment:
      NODE_HOST: "gord3"
      EXIST_NODE_HOST: "gord2"