version: '2.0'

services:
  gord1:
    build: .
    ports:
      - "26040:26040"
      - "26041:26041"
    command: -l gord1
  gord2:
    build: .
    depends_on:
      - gord1
    ports:
      - "36040:26040"
      - "36041:26041"
    command: -l gord2 -n gord1
  gord3:
    build: .
    depends_on:
      - gord1
      - gord2
    ports:
      - "46040:26040"
      - "46041:26041"
    command: -l gord3 -n gord2