// Code generated by ogen, DO NOT EDIT.

package api_external

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ExternalServiceDeleteValue implements ExternalService_DeleteValue operation.
//
// POST /server.ExternalService/DeleteValue
func (UnimplementedHandler) ExternalServiceDeleteValue(ctx context.Context, req *ExternalServiceDeleteValueReq) (r *ServerDeleteValueResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ExternalServiceFindHostForKey implements ExternalService_FindHostForKey operation.
//
// POST /server.ExternalService/FindHostForKey
func (UnimplementedHandler) ExternalServiceFindHostForKey(ctx context.Context, req *ExternalServiceFindHostForKeyReq) (r *ServerNode, _ error) {
	return r, ht.ErrNotImplemented
}

// ExternalServiceGetValue implements ExternalService_GetValue operation.
//
// POST /server.ExternalService/GetValue
func (UnimplementedHandler) ExternalServiceGetValue(ctx context.Context, req *ExternalServiceGetValueReq) (r *ServerGetValueResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ExternalServicePutValue implements ExternalService_PutValue operation.
//
// POST /server.ExternalService/PutValue
func (UnimplementedHandler) ExternalServicePutValue(ctx context.Context, req *ExternalServicePutValueReq) (r *ServerPutValueResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
