openapi: 3.0.2
info:
  title: "server/public.proto"
  version: "version not set"
tags:
  - name: "ExternalService"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /server.ExternalService/DeleteValue:
    post:
      operationId: "ExternalService_DeleteValue"
      responses:
        200:
          description: "A successful response."
          content:
            application/json:
              schema:
                $ref: "#/definitions/serverDeleteValueResponse"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                key:
                  type: "string"
      tags:
        - "ExternalService"
  /server.ExternalService/FindHostForKey:
    post:
      operationId: "ExternalService_FindHostForKey"
      responses:
        200:
          description: "A successful response."
          content:
            application/json:
              schema:
                $ref: "#/definitions/serverNode"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                key:
                  type: "string"
      tags:
        - "ExternalService"
  /server.ExternalService/GetValue:
    post:
      operationId: "ExternalService_GetValue"
      responses:
        200:
          description: "A successful response."
          content:
            application/json:
              schema:
                $ref: "#/definitions/serverGetValueResponse"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                key:
                  type: "string"
      tags:
        - "ExternalService"
  /server.ExternalService/PutValue:
    post:
      operationId: "ExternalService_PutValue"
      responses:
        200:
          description: "A successful response."
          content:
            application/json:
              schema:
                $ref: "#/definitions/serverPutValueResponse"
        default:
          description: General Error
          content:
            application/json:
              schema:
                $ref: "#/definitions/Error"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                key:
                  type: "string"
                value:
                  type: "string"
      tags:
        - "ExternalService"
definitions:
  serverDeleteValueResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
  serverGetValueResponse:
    type: "object"
    properties:
      value:
        type: "string"
      success:
        type: "boolean"
  serverNode:
    type: "object"
    properties:
      host:
        type: "string"
  serverPutValueResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
  Error:
    description: Represents error object
    type: object
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
    required:
      - code
      - message