// Code generated by ogen, DO NOT EDIT.

package api_internal

import (
	"net/http"

	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func encodeInternalServiceDeleteValueInnerResponse(response *InternalServiceDeleteValueInnerOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceFindClosestPrecedingNodeResponse(response *InternalServiceFindClosestPrecedingNodeOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceFindSuccessorByListResponse(response *InternalServiceFindSuccessorByListOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceFindSuccessorByTableResponse(response *InternalServiceFindSuccessorByTableOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceGetValueInnerResponse(response *InternalServiceGetValueInnerOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceNotifyResponse(response *InternalServiceNotifyOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServicePingResponse(response *InternalServicePingOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServicePredecessorResponse(response *InternalServicePredecessorOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServicePutValueInnerResponse(response *InternalServicePutValueInnerOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}

func encodeInternalServiceSuccessorsResponse(response *InternalServiceSuccessorsOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)
	span.SetStatus(codes.Ok, http.StatusText(200))

	return nil
}
