// Code generated by ogen, DO NOT EDIT.

package api_internal

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// InternalServiceDeleteValueInner implements InternalService_DeleteValueInner operation.
	//
	// POST /server.InternalService/DeleteValueInner
	InternalServiceDeleteValueInner(ctx context.Context, params InternalServiceDeleteValueInnerParams) error
	// InternalServiceFindClosestPrecedingNode implements InternalService_FindClosestPrecedingNode operation.
	//
	// POST /server.InternalService/FindClosestPrecedingNode
	InternalServiceFindClosestPrecedingNode(ctx context.Context, params InternalServiceFindClosestPrecedingNodeParams) error
	// InternalServiceFindSuccessorByList implements InternalService_FindSuccessorByList operation.
	//
	// POST /server.InternalService/FindSuccessorByList
	InternalServiceFindSuccessorByList(ctx context.Context, params InternalServiceFindSuccessorByListParams) error
	// InternalServiceFindSuccessorByTable implements InternalService_FindSuccessorByTable operation.
	//
	// POST /server.InternalService/FindSuccessorByTable
	InternalServiceFindSuccessorByTable(ctx context.Context, params InternalServiceFindSuccessorByTableParams) error
	// InternalServiceGetValueInner implements InternalService_GetValueInner operation.
	//
	// POST /server.InternalService/GetValueInner
	InternalServiceGetValueInner(ctx context.Context, params InternalServiceGetValueInnerParams) error
	// InternalServiceNotify implements InternalService_Notify operation.
	//
	// POST /server.InternalService/Notify
	InternalServiceNotify(ctx context.Context, params InternalServiceNotifyParams) error
	// InternalServicePing implements InternalService_Ping operation.
	//
	// POST /server.InternalService/Ping
	InternalServicePing(ctx context.Context) error
	// InternalServicePredecessor implements InternalService_Predecessor operation.
	//
	// POST /server.InternalService/Predecessor
	InternalServicePredecessor(ctx context.Context) error
	// InternalServicePutValueInner implements InternalService_PutValueInner operation.
	//
	// POST /server.InternalService/PutValueInner
	InternalServicePutValueInner(ctx context.Context, params InternalServicePutValueInnerParams) error
	// InternalServiceSuccessors implements InternalService_Successors operation.
	//
	// POST /server.InternalService/Successors
	InternalServiceSuccessors(ctx context.Context) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
