// Code generated by ogen, DO NOT EDIT.

package api_internal

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ExternalServiceDeleteValue implements ExternalService_DeleteValue operation.
//
// POST /server.ExternalService/DeleteValue
func (UnimplementedHandler) ExternalServiceDeleteValue(ctx context.Context, params ExternalServiceDeleteValueParams) error {
	return ht.ErrNotImplemented
}

// ExternalServiceFindHostForKey implements ExternalService_FindHostForKey operation.
//
// POST /server.ExternalService/FindHostForKey
func (UnimplementedHandler) ExternalServiceFindHostForKey(ctx context.Context, params ExternalServiceFindHostForKeyParams) error {
	return ht.ErrNotImplemented
}

// ExternalServiceGetValue implements ExternalService_GetValue operation.
//
// POST /server.ExternalService/GetValue
func (UnimplementedHandler) ExternalServiceGetValue(ctx context.Context, params ExternalServiceGetValueParams) error {
	return ht.ErrNotImplemented
}

// ExternalServicePutValue implements ExternalService_PutValue operation.
//
// POST /server.ExternalService/PutValue
func (UnimplementedHandler) ExternalServicePutValue(ctx context.Context, params ExternalServicePutValueParams) error {
	return ht.ErrNotImplemented
}
