// Code generated by ogen, DO NOT EDIT.

package api_internal

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// InternalServiceDeleteValueInner implements InternalService_DeleteValueInner operation.
//
// POST /server.InternalService/DeleteValueInner
func (UnimplementedHandler) InternalServiceDeleteValueInner(ctx context.Context, req *InternalServiceDeleteValueInnerReq) error {
	return ht.ErrNotImplemented
}

// InternalServiceFindClosestPrecedingNode implements InternalService_FindClosestPrecedingNode operation.
//
// POST /server.InternalService/FindClosestPrecedingNode
func (UnimplementedHandler) InternalServiceFindClosestPrecedingNode(ctx context.Context, req *InternalServiceFindClosestPrecedingNodeReq) (r *ServerNode, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServiceFindSuccessorByList implements InternalService_FindSuccessorByList operation.
//
// POST /server.InternalService/FindSuccessorByList
func (UnimplementedHandler) InternalServiceFindSuccessorByList(ctx context.Context, req *InternalServiceFindSuccessorByListReq) (r *ServerNode, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServiceFindSuccessorByTable implements InternalService_FindSuccessorByTable operation.
//
// POST /server.InternalService/FindSuccessorByTable
func (UnimplementedHandler) InternalServiceFindSuccessorByTable(ctx context.Context, req *InternalServiceFindSuccessorByTableReq) (r *ServerNode, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServiceGetValueInner implements InternalService_GetValueInner operation.
//
// POST /server.InternalService/GetValueInner
func (UnimplementedHandler) InternalServiceGetValueInner(ctx context.Context, req *InternalServiceGetValueInnerReq) (r *ServerGetValueInnerResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServiceNotify implements InternalService_Notify operation.
//
// POST /server.InternalService/Notify
func (UnimplementedHandler) InternalServiceNotify(ctx context.Context, req *InternalServiceNotifyReq) (r *ServerSuccessResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServicePing implements InternalService_Ping operation.
//
// POST /server.InternalService/Ping
func (UnimplementedHandler) InternalServicePing(ctx context.Context) (r *ServerSuccessResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServicePredecessor implements InternalService_Predecessor operation.
//
// POST /server.InternalService/Predecessor
func (UnimplementedHandler) InternalServicePredecessor(ctx context.Context) (r *ServerNode, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServicePutValueInner implements InternalService_PutValueInner operation.
//
// POST /server.InternalService/PutValueInner
func (UnimplementedHandler) InternalServicePutValueInner(ctx context.Context, req *InternalServicePutValueInnerReq) (r *ServerPutValueInnerResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// InternalServiceSuccessors implements InternalService_Successors operation.
//
// POST /server.InternalService/Successors
func (UnimplementedHandler) InternalServiceSuccessors(ctx context.Context) (r *ServerNodes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
