// Code generated by ogen, DO NOT EDIT.

package api_internal

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/server.InternalService/"
			if l := len("/server.InternalService/"); len(elem) >= l && elem[0:l] == "/server.InternalService/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'D': // Prefix: "DeleteValueInner"
				if l := len("DeleteValueInner"); len(elem) >= l && elem[0:l] == "DeleteValueInner" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleInternalServiceDeleteValueInnerRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
			case 'F': // Prefix: "Find"
				if l := len("Find"); len(elem) >= l && elem[0:l] == "Find" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'C': // Prefix: "ClosestPrecedingNode"
					if l := len("ClosestPrecedingNode"); len(elem) >= l && elem[0:l] == "ClosestPrecedingNode" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleInternalServiceFindClosestPrecedingNodeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
				case 'S': // Prefix: "SuccessorBy"
					if l := len("SuccessorBy"); len(elem) >= l && elem[0:l] == "SuccessorBy" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'L': // Prefix: "List"
						if l := len("List"); len(elem) >= l && elem[0:l] == "List" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleInternalServiceFindSuccessorByListRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}
					case 'T': // Prefix: "Table"
						if l := len("Table"); len(elem) >= l && elem[0:l] == "Table" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleInternalServiceFindSuccessorByTableRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}
					}
				}
			case 'G': // Prefix: "GetValueInner"
				if l := len("GetValueInner"); len(elem) >= l && elem[0:l] == "GetValueInner" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleInternalServiceGetValueInnerRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
			case 'N': // Prefix: "Notify"
				if l := len("Notify"); len(elem) >= l && elem[0:l] == "Notify" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleInternalServiceNotifyRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
			case 'P': // Prefix: "P"
				if l := len("P"); len(elem) >= l && elem[0:l] == "P" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ing"
					if l := len("ing"); len(elem) >= l && elem[0:l] == "ing" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleInternalServicePingRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
				case 'r': // Prefix: "redecessor"
					if l := len("redecessor"); len(elem) >= l && elem[0:l] == "redecessor" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleInternalServicePredecessorRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
				case 'u': // Prefix: "utValueInner"
					if l := len("utValueInner"); len(elem) >= l && elem[0:l] == "utValueInner" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleInternalServicePutValueInnerRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "POST")
						}

						return
					}
				}
			case 'S': // Prefix: "Successors"
				if l := len("Successors"); len(elem) >= l && elem[0:l] == "Successors" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "POST":
						s.handleInternalServiceSuccessorsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
			}
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [0]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/server.InternalService/"
			if l := len("/server.InternalService/"); len(elem) >= l && elem[0:l] == "/server.InternalService/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'D': // Prefix: "DeleteValueInner"
				if l := len("DeleteValueInner"); len(elem) >= l && elem[0:l] == "DeleteValueInner" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						// Leaf: InternalServiceDeleteValueInner
						r.name = "InternalServiceDeleteValueInner"
						r.summary = ""
						r.operationID = "InternalService_DeleteValueInner"
						r.pathPattern = "/server.InternalService/DeleteValueInner"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
			case 'F': // Prefix: "Find"
				if l := len("Find"); len(elem) >= l && elem[0:l] == "Find" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'C': // Prefix: "ClosestPrecedingNode"
					if l := len("ClosestPrecedingNode"); len(elem) >= l && elem[0:l] == "ClosestPrecedingNode" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							// Leaf: InternalServiceFindClosestPrecedingNode
							r.name = "InternalServiceFindClosestPrecedingNode"
							r.summary = ""
							r.operationID = "InternalService_FindClosestPrecedingNode"
							r.pathPattern = "/server.InternalService/FindClosestPrecedingNode"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
				case 'S': // Prefix: "SuccessorBy"
					if l := len("SuccessorBy"); len(elem) >= l && elem[0:l] == "SuccessorBy" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'L': // Prefix: "List"
						if l := len("List"); len(elem) >= l && elem[0:l] == "List" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								// Leaf: InternalServiceFindSuccessorByList
								r.name = "InternalServiceFindSuccessorByList"
								r.summary = ""
								r.operationID = "InternalService_FindSuccessorByList"
								r.pathPattern = "/server.InternalService/FindSuccessorByList"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
					case 'T': // Prefix: "Table"
						if l := len("Table"); len(elem) >= l && elem[0:l] == "Table" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								// Leaf: InternalServiceFindSuccessorByTable
								r.name = "InternalServiceFindSuccessorByTable"
								r.summary = ""
								r.operationID = "InternalService_FindSuccessorByTable"
								r.pathPattern = "/server.InternalService/FindSuccessorByTable"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
					}
				}
			case 'G': // Prefix: "GetValueInner"
				if l := len("GetValueInner"); len(elem) >= l && elem[0:l] == "GetValueInner" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						// Leaf: InternalServiceGetValueInner
						r.name = "InternalServiceGetValueInner"
						r.summary = ""
						r.operationID = "InternalService_GetValueInner"
						r.pathPattern = "/server.InternalService/GetValueInner"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
			case 'N': // Prefix: "Notify"
				if l := len("Notify"); len(elem) >= l && elem[0:l] == "Notify" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						// Leaf: InternalServiceNotify
						r.name = "InternalServiceNotify"
						r.summary = ""
						r.operationID = "InternalService_Notify"
						r.pathPattern = "/server.InternalService/Notify"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
			case 'P': // Prefix: "P"
				if l := len("P"); len(elem) >= l && elem[0:l] == "P" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "ing"
					if l := len("ing"); len(elem) >= l && elem[0:l] == "ing" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							// Leaf: InternalServicePing
							r.name = "InternalServicePing"
							r.summary = ""
							r.operationID = "InternalService_Ping"
							r.pathPattern = "/server.InternalService/Ping"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
				case 'r': // Prefix: "redecessor"
					if l := len("redecessor"); len(elem) >= l && elem[0:l] == "redecessor" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							// Leaf: InternalServicePredecessor
							r.name = "InternalServicePredecessor"
							r.summary = ""
							r.operationID = "InternalService_Predecessor"
							r.pathPattern = "/server.InternalService/Predecessor"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
				case 'u': // Prefix: "utValueInner"
					if l := len("utValueInner"); len(elem) >= l && elem[0:l] == "utValueInner" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							// Leaf: InternalServicePutValueInner
							r.name = "InternalServicePutValueInner"
							r.summary = ""
							r.operationID = "InternalService_PutValueInner"
							r.pathPattern = "/server.InternalService/PutValueInner"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
				}
			case 'S': // Prefix: "Successors"
				if l := len("Successors"); len(elem) >= l && elem[0:l] == "Successors" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						// Leaf: InternalServiceSuccessors
						r.name = "InternalServiceSuccessors"
						r.summary = ""
						r.operationID = "InternalService_Successors"
						r.pathPattern = "/server.InternalService/Successors"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
			}
		}
	}
	return r, false
}
